### ISSUE TITLE
Post json to Slack

### ISSUE THREAD

**Issue by Johnny79** [bentleymi/ta-webtools#10]
Hi Michael,

Great job on the SPL `| curl` command! It's exacly what I need.

I'm having some trouble posting a json payload to slack and can't figure out what I'm doing wrong.

Slack wants to receive it like this.
`{"text":"test"}`

I've created this SPL to post the json string to a slack webhook.
```
| makeresults 
| eval uri="https://hooks.slack.com/services/***/***/***"
| eval data="{\"text\":\"test\"}"
| eval header="{\"content-type\":\"application/json\"}"
| curl method=post urifield=uri datafield=data headerfield=header
```

This results in an invalid payload.

When I check the result of the post with https://requestbin.com/ It looks like the data went out as a query string instead of a json string.
`text=test`

With a little creativity I got it to work for 99% with single quotes but that's not the right way I think and causes a problem when there are single quotes in a piece of text.
`data="{'text':'test'}"`

Hope you can help me out with this. Let me know if you need more info on this.

**Comment by Johnny79** [comment]
I changed data=payload to json=payload on line 78 in curl.py and now it's sending the right json format

```
def post(uri,sessionKey,verifyssl,cert,headers=None,payload=None,user=None,password=None,timeout=60):
    try:
        if sessionKey == None:
            if user == None and password == None:
                r = requests.post(uri,json=payload,verify=verifyssl,cert=cert,headers=headers,timeout=timeout)
```

**Comment by Serinu** [comment]
@Johnny79 : I hadn't seen it before, but basically, this relates to (more recent) issue #15 . Suggestions for improvements have been made there already. So I think, @bentleymi can close this issue as well.

**Comment by bentleymi** [comment]
Closing as per Srinu.
