### ISSUE TITLE
url encode command

### ISSUE THREAD

**Issue by Johnny79** [bentleymi/ta-webtools#11]
Hi,

Look like the urlencode command doesn't work?

**My SPL**
```
| makeresults 
| eval field="encode this"
| urlencode field
```
**Response**
```
ERROR
name 'urllib' is not defined
```

It also doesn't turn blue like the other SPL commands.

**Comment by dmarlingSplunk** [comment]
The quick fix for this is to modify line 17 to `import six.moves.urllib as urllib` and line 27 to `return urllib.parse.quote_plus(s)` in the urlencode.py file in the bin folder.

**Comment by gjanders** [comment]
Or try https://github.com/bentleymi/ta-webtools/pull/21 :)

**Comment by dmarlingSplunk** [comment]
Thanks Gareth.  I should look at PR's before I type things! :)

**Comment by bentleymi** [comment]
Folded in the fix in the latest release:  https://github.com/bentleymi/ta-webtools/blob/cloud-version/TA-webtools/bin/urlencode.py

Thanks all!
