### ISSUE TITLE
Data which were set in options will be nullified in the next if statement

### ISSUE THREAD

**Issue by grauwolf32** [bentleymi/ta-webtools#12]
Hi, Michael
It seems that these lines of code of the curl.py are placed in the wrong order:

` 

                  if 'data' in options:  # ! If data is set here
                        data = str(options['data'])

                    # if datafield in options, set datafield = options['datafield']
                    if 'datafield' in options:
                        try:
                            data = json.loads(result[options['datafield']])
                        except:
                            data = str(result[options['datafield']])
                    else:
                        data = None  # ! There it will be nullified

`

If data were set in options, then it will be nullified in the next if statement.

**Comment by bentleymi** [comment]
You can specify data="data here" OR datafield=fieldnameFromYourSearch, but not both.

This is the desired behavior.
