### ISSUE TITLE
Not able to do Curl on Datadog APi

### ISSUE THREAD

**Issue by vishaltaneja07011993** [bentleymi/ta-webtools#13]
Hey ,

Good Morning.

I am not able to do curl on datadog api using curl command. in search.log able to see error like:

03-15-2021 09:32:07.577 ERROR ScriptRunner - stderr from '/opt/splunk/bin/python3.7 /opt/splunk/etc/apps/TA-webtools/bin/curl.py urifield=uri verifySSL=false debug=true':  /opt/splunk/lib/python3.7/site-packages/urllib3/connectionpool.py:851: InsecureRequestWarning: Unverified HTTPS request is being made. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#ssl-warnings
03-15-2021 09:32:07.577 ERROR ScriptRunner - stderr from '/opt/splunk/bin/python3.7 /opt/splunk/etc/apps/TA-webtools/bin/curl.py urifield=uri verifySSL=false debug=true':    InsecureRequestWarning)
03-15-2021 09:32:07.613 INFO  script - Invoked script curl with 1809 input bytes (1 events).  Returned 21056227 output bytes in 7808 ms.
03-15-2021 09:32:07.762 INFO  PreviewExecutor - Stopping preview triggers since search almost finished

Even i have tried with verifyssl=true still didn't work out same error.

And also its not showing any event.

Could you please help?

**Comment by bentleymi** [comment]
For problems like this, please report them on community.splunk.com.  It should be resolved in the latest cloud-version branch that forces everything to be verified SSL/TLS 

fix your datadog api cert.  insecure is not even ok for development and testing these days.  Always harden web ports before first login.
