### ISSUE TITLE
method PATCH missing?  (-X PATCH)

### ISSUE THREAD

**Issue by kerdefin** [bentleymi/ta-webtools#14]
Hi,
Tried something like this:
| curl method=patch urifield=urli headerfield=header datafield=data

and I have \"Content-Type\":\"application/json-patch+json\" on headers.. etc.

Method PATCH is absent. Is there any chance to get that included? thnx!

**Comment by bojanjanisch** [comment]
Please bump this issue. Should not be difficult to implement analyzing the source code.

**Comment by bentleymi** [comment]
We accept pull requests from budding developers that also want to sacrifice their time for the community.

**Comment by bentleymi** [comment]
Patch was added a release or two ago, but i didnt close this issue then.

https://github.com/bentleymi/ta-webtools/blob/cloud-version/TA-webtools/bin/curl.py

**Comment by bentleymi** [comment]
Patch was added a release or two ago, but i didnt close this issue then.

https://github.com/bentleymi/ta-webtools/blob/cloud-version/TA-webtools/bin/curl.py
https://github.com/bentleymi/ta-webtools/blob/master/TA-webtools/bin/curl.py
