### ISSUE TITLE
Setting the Authorization header on the modular input doesn't work

### ISSUE THREAD

**Issue by abedegno** [bentleymi/ta-webtools#20]
When setting the custom request header on a modular input and defining an Authorization header  (e.g. for bearer/token authentication) the header is not including in the request.

This is because the username/password is always passed into the requests.request call-forcing basic authentication.  Pull request #19 fixes this by including an additional check on the username/password and passing None into the requests.request call if they are empty.

**Comment by bentleymi** [comment]
Merged a while back
