### ISSUE TITLE
App page returns 500 internal server error when opened.

### ISSUE THREAD

**Issue by arpitsaxena12** [bentleymi/ta-webtools#22]
Getting :

Unable to initialize modular input "log_analytics" defined in the app "TA-ms_loganalytics": Introspecting scheme=log_analytics: script running failed (PID 71116 exited with code 1)..

The app page returns 500 internal server error when opened.

**Comment by Serinu** [comment]
@arpitsaxena12 : This is no issue of ta-webtools. Please use the correct repository when submitting issues.

**Comment by bentleymi** [comment]
That is correct, please move this issue to https://github.com/bentleymi/ta-ms_loganalytics
