### ISSUE TITLE
urlencode command is not accessible even with the permissions set to Global and the getting syntax errors.

### ISSUE THREAD

**Issue by sumang99** [bentleymi/ta-webtools#25]
Error: Unknown search command 'urlencode'.

**Comment by bentleymi** [comment]
This works fine on version 3.0.2:

![image](https://user-images.githubusercontent.com/4107863/212722819-1a829da0-cc93-4275-99d2-5b7a1a15ff80.png)

**Comment by bentleymi** [comment]
Please use the latest version (3.0.2 currently):
https://github.com/bentleymi/ta-webtools/tree/cloud-version  
https://splunkbase.splunk.com/app/4146/
