### ISSUE TITLE
Webtools on SplunkEnterprise on Windows OS

### ISSUE THREAD

**Issue by Falko-egt** [bentleymi/ta-webtools#26]
The SSL certificate verification does not work on Windows, I get this error (SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1106)')))) although our internal connections are all secured via SSL. The same error occurs with a native curl program under windows until you give it the root certificates of our CA in the curl-ca-bundle.crt. Is it possible to integrate this into the webtools?

Translated with www.DeepL.com/Translator (free version)

**Comment by bentleymi** [comment]
As we discussed over email, by default python uses your trusted root store.  So certificate issue is not a problem with the app but with your servers certificate or python configurations.  Your trusted root store could be missing any cert that's in the chain.  Maybe your python is using a different cert store somehow.

you can try older versions of the app that allow you to specify certs or set verify=false (which is not recommend of course).

you can also try simple requests from a python shell.

import requests
r = requests.get(url, verify=True)
r.text
