### ISSUE TITLE
TA-Webtool Add-on CURL command execution causing excess Splunk knowledge object deletion with using "Method=Delete"

### ISSUE THREAD

**Issue by sumang99** [bentleymi/ta-webtools#31]
**Name of the app**
TA-Webtools Add-on

**Describe the bug**
- We use CURL command which is part of the TA-Webtools App that's installed on standalone search head that can make Rest calls to SHC using Splunk Auth token.
- Once we ran the curl command, we expect to see a http status code 200 along with a XML response indicating the object deletion.
- We did run a GET before running DELETE and both the time the results count is same, but the internal logs show more than double the number of expected deletions.
- We are not sure how to reproduce this issue without impacting the environment since this is not visible to show how this happened in 1st place.

**To Reproduce**
1. Run the CURL command from Web UI with method=DELETE and check "curl_status" code 
2. Check the internal audit logs for SID to find the result count.
3. Now run this below search to find the actual impacted KO's 
 index=_* uri_path="*" user=* status=200 method=DELETE
| stats dc(uri_path)

4. Please let us know if you've already seen this issue with this app before.

**Comment by bentleymi** [comment]
What is the search you use with delete?

Is it using | curl as a streaming or generating command?

By chance are you passing a list of KOs to be deleted?

Thanks,
Michael


On Jun 19, 2024, at 9:35 AM, sumang99 ***@***.***> wrote:

﻿


Name of the app
TA-Webtools Add-on

Describe the bug

*	We use CURL command which is part of the TA-Webtools App that's installed on standalone search head that can make Rest calls to SHC using Splunk Auth token.
*	Once we ran the curl command, we expect to see a http status code 200 along with a XML response indicating the object deletion.
*	We did run a GET before running DELETE and both the time the results count is same, but the internal logs show more than double the number of expected deletions.
*	We are not sure how to reproduce this issue without impacting the environment since this is not visible to show how this happened in 1st place.

To Reproduce
Steps to reproduce the behavior:

1.	

Run the CURL command from Web UI with method=DELETE and check "curl_status" code

2.	

Check the internal audit logs for SID to find the result count.

3.	

Now run this below search to find the actual impacted KO's
index=_* uri_path="" user= status=200 method=DELETE
| stats dc(uri_path)

4.	

Please let us know if you've already seen this issue with this app before.

**Comment by sumang99** [comment]
Michael, I'm using summary data to build the required attributes and then at the end using the curl command as shown below.
-  Header field has auth token. 
- Tested this with GET to find the numbers of results and status codes and then ran the DELETE.
| curl urifield=url method=DELETE headerfield=header

**Comment by bentleymi** [comment]
Ok so you're using it as a streaming command.

What URL are you passing it?  Can you give me an example of a URL given with delete that caused multiple deletes?

On Jun 19, 2024, at 4:34 PM, sumang99 ***@***.***> wrote:

﻿


Michael, I'm using summary data to build the required attributes and then at the end using the curl command as shown below.

*	Header field has auth token.
*	Tested this with GET to find the numbers of results and status codes and then ran the DELETE.
| curl urifield=url method=DELETE headerfield=header

**Comment by sumang99** [comment]
Here is an example of how our url looks like Example URL: https://hostname.splunkcloud.com:8089/servicesNS/username/search/saved/searches/Buildlookup%20list 

Each knowledge object has a unique url created with the owner of the object/appname/saved searchname

**Comment by bentleymi** [comment]
i don't see how it could possibly delete a bunch of random KOs given that you have to DELETE each one via it's very specific endpoint.

I'll try to replicate it though.

On Jun 19, 2024, at 6:49 PM, sumang99 ***@***.***> wrote:

﻿


Here is an example of how our url looks like Example URL: https://hostname.splunkcloud.com:8089/servicesNS/username/search/saved/searches/Buildlookup%20list <https://hostname.splunkcloud.com:8089/servicesNS/username/search/saved/searches/Buildlookup%20list> 

Each knowledge object has a unique url created with the owner of the object/appname/saved searchname

**Comment by sumang99** [comment]
Please keep us posted if you've any findings. This is something we use in our production and has recently caused impact.

**Comment by sumang99** [comment]
Any updates on the above-mentioned issue?

**Comment by bentleymi** [comment]
It should only occur if you gave it the url of the KO you wanted to delete.

I've tested without any issue on my end.

On Jun 27, 2024, at 1:40 PM, sumang99 ***@***.***> wrote:

﻿


Any updates on the above-mentioned issue?

**Comment by sumang99** [comment]
Just wants to make sure I understand the above comments. So, you're saying that if we use the direct URL for a KO to delete the object, we will experience this behavior? If that's the case what's the best approach to tackle bulk deletions? Do you know why it's behaving like this for Method=Delete and does it impact method GET and POST? Also, any plans to fix this issue?

**Comment by bentleymi** [comment]
I'm saying you made a mistake in your search.  

The command will never "randomly delete". 

It will only use "delete" once per invocation.

The delete function is exactly the same as the POST, GET, HEAD, and other functions.  You can see for yourself:

https://github.com/bentleymi/ta-webtools/blob/66e92cacf49a3c146d9ff4985de7268d0e9b9ef5/TA-webtools/bin/curl.py#L46-L135

The only way the condition you describe occurred is if you were using the command as a streaming command, and you streamed the wrong URIs to it via urifield=$variable$ or similar issue.

There is nothing to fix in the code. PEBCAK?

**Comment by sumang99** [comment]
Apologies on miss interpreting your response. As I have mentioned above, I did a GET call to conform the URL's we're passing to CURL to validate the response code 200 which gave us the exact count of KO's we have targeted and then changed the CURL method to Delete and the result count match with GET response and that's all summarized. But the Delete has removed more than what we have expected, and I did review this with my team and as well as Splunk support and everyone agrees with the analysis and results.

**Comment by bentleymi** [comment]
I wasnt able to replicate with the details provided.

**1. Create a search called "test"**
**2. Curl to get it & Curl to delete it**

SPL `append` will actually execute the subsearch first, so we put the get in a subsearch and the delete in the main search:

```
| makeresults count=1
| fields - _time
| eval uri="https://localhost:8443/en-US/splunkd/__raw/servicesNS/admin/search/saved/searches/test?test=DELETE"
| curl urifield=uri splunkauth=true verifyssl=false method=DELETE
| rename curl_* as *_DELETE
| appendcols 
 [
 | makeresults count=1
 | fields - _time
 | eval uri="https://localhost:8443/en-US/splunkd/__raw/servicesNS/admin/search/saved/searches/test?test=GET"
 | curl urifield=uri splunkauth=true verifyssl=false method=GET
 | rename curl_* as *_GET
 ]
```

**3. Check internal log for results:**

```
index=_internal   status=* test uri_path="/en-US/splunkd/__raw/servicesNS/admin/search/saved/searches/test"
```

**4. Results: Just one (1) DELETE**  
```
127.0.0.1 - - [02/Jul/2024:13:39:44.452 -0400] "GET /en-US/splunkd/__raw/servicesNS/admin/search/saved/searches/test?test=DELETE HTTP/1.1" 200 13515 "-" "python-requests/2.25.0" - - 1ms
127.0.0.1 - - [02/Jul/2024:13:39:44.450 -0400] "DELETE /en-US/splunkd/__raw/servicesNS/admin/search/saved/searches/test?test=DELETE HTTP/1.1" 303 127 "-" "python-requests/2.25.0" - - 0ms
 127.0.0.1 - - [02/Jul/2024:13:39:41.706 -0400] "GET /en-US/splunkd/__raw/servicesNS/admin/search/saved/searches/test?test=GET HTTP/1.1" 200 13516 "-" "python-requests/2.25.0" - - 1ms
 127.0.0.1 - - [02/Jul/2024:13:39:41.704 -0400] "GET /en-US/splunkd/__raw/servicesNS/admin/search/saved/searches/test?test=GET HTTP/1.1" 303 127 "-" "python-requests/2.25.0" - - 0ms
```
