### ISSUE TITLE
PR: Sleep parameter together with urifield

### ISSUE THREAD

**Issue by OOaker** [bentleymi/ta-webtools#4]
First of all thanks for the great app. It works great and allows us to use all those juicy security API’s for our Splunk based SIEM.
The only thing I’m missing is a “sleep” parameter if “urifield” is used. Many API have rate limitations and allow a query only every few seconds. There is some SPL kung-fu that can be used to mitigate the issue but it’s rather cumbersome. I think I will be able to adjust your app easily by myself but maybe other people might find such a feature useful as well. Oh and Splunk 8.x support would be swell as well. ;-)

"| curl method=get urifield=url headerfield=header timeout=2 sleep=1000"
Sleep = wait for 1000 milliseconds between curl requests.

**Comment by bentleymi** [comment]
Do you want to try to branch the code make edits and create a PR?

If not, it may be a moment.  I still have a PR in front of you to test and merge.

**Comment by OOaker** [comment]
Okay, I might try. Depends a bit on my workload atm so I can't guarantee anything unfortunately.

**Comment by bentleymi** [comment]
im closing this repo, moving to https://github.com/bentleymi/ta-webtools where it should have been to start with

**Comment by bentleymi** [comment]
Figured out how to rename it instead.

**Comment by bentleymi** [comment]
https://github.com/bentleymi/ta-webtools/blob/master/TA-webtools/bin/curl.py

updated with sleep option, will be folded into v2.0.1 release

**Comment by bentleymi** [comment]
https://splunkbase.splunk.com/app/4146/
