### ISSUE TITLE
ITSI Maintenance Windows via REST using Web Tools Add-on not working

### ISSUE THREAD

**Issue by nickmew0** [bentleymi/ta-webtools#5]
Have being trying out the Web tool add-on to do some maintenance on ITSI objects with the ITSI REST api.

I've managed to do make some of the options work - like enabling and disabling services, but I'm stuck on creating maintenance windows.

Using a standard command line curl I've managed to create a maintenance window works

curl -k -u <user>:<password> https://<server>:<port>/servicesNS/nobody/SA-ITOA/maintenance_services_interface/maintenance_calendar -X POST -H "Content-Type:application/json" -d "{\"title\":\"TEST MW\",\"start_time\":1589715600,\"end_time\":1589719600,\"objects\":[{\"object_type\":\"service\",\"_key\":\"<serviceid>\"}]}

but trying to use this within SPL is failing :

index=itsi_summary
| head 1
| eval header="{\"content-type\":\"application/json\"}"
| eval data="{\"title\":\"TEST MW2\",\"start_time\":1589705600,\"end_time\":1589709600,\"objects\":[{\"object_type\":\"entity\",\"_key\":\"<serviceid>\"}]}"
| curl method=post uri=https://localhost:8089//servicesNS/nobody/SA-ITOA/maintenance_services_interface/maintenance_calendar splunkauth=true debug=false headerfield=header datafield=data

should be materially the same (barring changing the title so it doesn't duplicate the command line curl), but I get a failure

{"message":"(400, 'Objects specified must be a valid non-empty list. Must specify at least one object.')"}

I've tried a variety of ways of fiddling with syntax but just can't get it to work - 

Confirmed by yourself on Splunk answers, something to do with SPL filter mechanisms and nested dictionaries in json.

https://docs.splunk.com/Documentation/ITSI/4.6.1/RESTAPI/ITSIRESTAPIschema#Maintenance_Calendar

**Comment by bentleymi** [comment]
Thanks for reporting the error, i'll work on this asap

**Comment by bentleymi** [comment]
i looked into this but didnt have any luck as of yet

**Comment by nickmew0** [comment]
> i looked into this but didnt have any luck as of yet

Hiya - thanks for looking at it. In the end for what I needed I worked around it - rather than using ITSI maintenance windows I created my own set in continuously updated lookups from our change data, and tweaked KPIs / dashboards to pay attention to those. Actually allowed me to be more flexible in the way I dealt with maintenance windows, and show visibilty of how broken things were during the window whilst not treating it as an issue, helping to see if changes had worked OK
