### ISSUE TITLE
Splunk v8 compatability

### ISSUE THREAD

**Issue by dmarlingSplunk** [bentleymi/ta-webtools#6]
Hi @bentleymi, We spoke over slack but I wanted to document it here as well.  We are using this application on our 7.3 splunk installation and will be moving to 8 in the near future and would like to continue to use your app.  Please use this issue to document that request.  Thank you!

**Comment by gliptak** [comment]
As a first step, might need to bring these (more) current in the project:

https://github.com/splunk/addonfactory-solutions-library-python
https://pypi.org/project/splunktaucclib/

I'm not sure if this is to happen using the Add-On Builder

**Comment by bentleymi** [comment]
I can make it work ;-) just have to port it to the latest AoB.

**Comment by bentleymi** [comment]
The app now supports v8

**Comment by dmarlingSplunk** [comment]
Awesome!  Thank you!
